In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
test_hmm = pd.read_pickle('/data/longterm/10/athira/selected_694exps_for_hmm.pkl')

In [3]:
test_hmm.head()

,frames,filename,drug,light,curv_head,speed_x_head,speed_y_head,speed_head,tan_head,angvel_head,...,rel_tan_tail_mid,rel_tan_tail_post_mid,rel_tan_tail_tip,ects_1,ects_2,ects_3,ects_4,ects_5,ects_6,quirkness
0,0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None,None,0.058707,0.021162,0.009879,0.023354,3.480727,-0.174167,...,0.158320,0.220058,0.273023,-0.032773,-0.293165,0.211007,0.099321,-0.111924,0.010923,0.998509
1,7,20180926_130524_1_5m0s_None_None_None_INVERTED...,None,None,0.185852,0.001883,-0.003767,0.004211,2.261559,-0.174167,...,1.441173,1.424161,1.495728,-0.032751,-0.279693,0.206679,0.098327,-0.100417,0.014764,0.998491
2,9,20180926_130524_1_5m0s_None_None_None_INVERTED...,None,None,0.183474,-0.005768,0.011505,0.012870,2.251235,-0.005162,...,1.434518,1.421028,1.528618,-0.031409,-0.275168,0.201922,0.097524,-0.094107,0.026631,0.998512
3,12,20180926_130524_1_5m0s_None_None_None_INVERTED...,None,None,0.093225,-0.624695,-0.373576,0.727875,3.239860,0.329542,...,0.467484,0.413798,0.533991,-0.028400,-0.256387,0.182410,0.076177,-0.077722,0.006339,0.998022
4,14,20180926_130524_1_5m0s_None_None_None_INVERTED...,None,None,0.185252,1.813354,0.976379,2.059508,2.405923,-0.416968,...,1.297722,1.234784,1.322084,-0.035836,-0.269816,0.218635,0.094795,-0.077012,0.021990,0.997847

In [7]:
hmm_motifs = pd.read_pickle('/share/devops/athira/project_behaviour/Data/motifs_dataframe_1743seenControl694_10model1743_normed.pkl')

In [8]:
hmm_motifs.head()

,start,stop,duration,cluster,filename,drug
0,743.0,789.0,46.0,0.0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None
1,3764.0,3766.0,2.0,0.0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None
2,3772.0,3782.0,10.0,0.0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None
3,3784.0,4797.0,1013.0,0.0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None
4,5002.0,5055.0,53.0,0.0,20180926_130524_1_5m0s_None_None_None_INVERTED...,None

In [9]:
test_tsne = pd.read_pickle('/data/longterm/10/athira/Jan26_preSeminarResults/tsne_control_results_clus.pkl')

In [10]:
test_tsne.head()

,filename,frames,tsne_proj_0,tsne_proj_1,clus_db
0,20180926_130524_1_5m0s_None_None_None_INVERTED...,0,-40.536146,-10.522207,1
1,20180926_130524_1_5m0s_None_None_None_INVERTED...,7,-41.142905,-11.467784,1
2,20180926_130524_1_5m0s_None_None_None_INVERTED...,9,-41.178663,-11.632881,1
3,20180926_130524_1_5m0s_None_None_None_INVERTED...,12,-41.556846,-11.854396,1
4,20180926_130524_1_5m0s_None_None_None_INVERTED...,14,-41.790240,-11.933108,1

In [11]:
len(test_tsne.index)

6603509

In [3]:
hmm_motifs_light = pd.read_pickle('/share/devops/athira/project_behaviour/Data/motifs_dataframe_1743SeenLightQTested150_10model1743_normed.pkl')

In [5]:
 
hmm_motifs_light_noDrug = hmm_motifs_light[hmm_motifs_light['drug']=='None']
hmm_motifs_light_noDrug

,start,stop,duration,cluster,filename,drug
0,9.0,11.0,2.0,0.0,20181210_140727_1_5m0s_None_None_Light_INVERTE...,None
0,12.0,345.0,333.0,4.0,20181210_140727_1_5m0s_None_None_Light_INVERTE...,None
0,0.0,7.0,7.0,6.0,20181210_140727_1_5m0s_None_None_Light_INVERTE...,None
1,349.0,349.0,0.0,6.0,20181210_140727_1_5m0s_None_None_Light_INVERTE...,None
0,8.0,8.0,0.0,7.0,20181210_140727_1_5m0s_None_None_Light_INVERTE...,None
...,...,...,...,...,...,...
6,1233.0,1233.0,0.0,8.0,20180919_145321_1_5m0s_None_None_Light_INVERTE...,None
7,2616.0,2617.0,1.0,8.0,20180919_145321_1_5m0s_None_None_Light_INVERTE...,None
0,336.0,336.0,0.0,9.0,20180919_145321_1_5m0s_None_None_Light_INVERTE...,None
1,4778.0,4778.0,0.0,9.0,20180919_145321_1_5m0s_None_None_Light_INVERTE...,None
2,4782.0,4782.0,0.0,9.0,20180919_145321_1_5m0s_None_None_Light_INVERTE...,None